version: '3.9'
services:
  nextapp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules  # 避免宿主机的 node_modules 覆盖容器内的
    environment:
      - NODE_ENV=development
